# Generated by Django 6.0 on 2025-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
