# Generated by Django 5.0.4 on 2024-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=5000)),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('numero_clase', models.IntegerField()),
            ],
        ),
    ]
