# Generated by Django 5.2.7 on 2025-10-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_dibujo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dibujo',
            name='fecha_Realizacion',
            field=models.DateField(),
        ),
    ]
